################
### MONITORS ###
################
# See https://wiki.hyprland.org/Configuring/Monitors/
$mon1 = HDMI-A-1
$mon2 = DP-3
monitor=$mon1, 1920x1080, 0x0, 1
monitor=$mon2, 1920x1200,-1200x-550, 1, transform, 1
