###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = kitty --class ranger-exp spf
$lazygit = kitty --class lazygit lazygit
# $menu = wofi --show drun
$menu = /home/afa/.config/rofi/launchers/type-7/launcher.sh
