##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

workspace = 1, monitor:$mon1, default:true
workspace = 2, monitor:$mon2, default:true
workspace = 3, monitor:$mon1
workspace = 4, monitor:$mon2
workspace = 5, monitor:$mon1
workspace = 6, monitor:$mon2
workspace = 7, monitor:$mon1
workspace = 8, monitor:$mon2
workspace = 9, monitor:$mon1
workspace = 10, monitor:$mon2



# Windows for clipboard manager clipse

windowrule = float on, match:class (clipse) # ensure you have a floating window class set if you want this behavior
windowrule = size 622 652,match:class (clipse) # set the size of the window as necessary

bind = SUPER, V, exec, kitty --class clipse -e 'clipse' 


# workspaces for certain applications
#explorer
workspace = special:explorer, on-created-empty:exec $fileManager
windowrule = workspace e+0, match:workspace = special:explorer

# Discord
workspace = special:discord, on-created-empty:exec discord
windowrule = workspace name:discord, match:class (discord)

# YT-Music
workspace = name:yt-music, monitor:$mon2
windowrule = workspace name:yt-music, match:initial_title ^(YouTube Music)$

# anytype
workspace = name:anytype, monitor:$mon1
windowrule = workspace name:anytype, match:class (anytype)$


# superProductivity
workspace = name:supProd, monitor:$mon2
windowrule = workspace name:supProd, match:class (superProductivity)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

cursor {
    no_hardware_cursors = true
}
